### ISSUE TITLE
Unable to install due to snapcraft error

### ISSUE THREAD

**Issue by aadilayub** [flathub/com.todoist.Todoist#25]
This error is also documented at https://github.com/flatpak/flatpak/issues/3919

Unlike the linked issue, I get this error both with and without sudo

```
~ took 11s 
❯ flatpak install todoist
Looking for matches…
Found ref ‘app/com.todoist.Todoist/x86_64/stable’ in remote ‘flathub’ (system).
Use this ref? [Y/n]: y

com.todoist.Todoist permissions:
    ipc           network      pulseaudio      x11     dri     dbus access [1]
    tags [2]

    [1] org.freedesktop.Notifications, org.freedesktop.secrets, org.kde.StatusNotifierWatcher
    [2] proprietary


        ID                           Branch          Op         Remote          Download
 1. [✗] com.todoist.Todoist          stable          i          flathub         1.0 kB / 92.5 MB

Error: While downloading https://api.snapcraft.io/api/v1/snaps/download/pP800io06HKwwkUmX8gDG1pFCfsinLHY_649.snap: Server returned status 503: Service Unavailable
error: Failed to install com.todoist.Todoist: While downloading https://api.snapcraft.io/api/v1/snaps/download/pP80
```

**Comment by jurf** [comment]
Can you download that file from your browser? If yes, this is a system or Flatpak issue, otherwise a Snap server infra one. Personally, I have never seen this, and looking at the [update stats](https://klausenbusk.github.io/flathub-stats/#ref=com.todoist.Todoist&interval=infinity&downloadType=updates) it works for many people, so my guess it is something specific to your setup/location.

Another thing you could try is to try to install Snap packages. If that fails too, you should probably report it to Snap devs.
